version: '3.8'

services:
  loan-prediction-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-prediction-api
    ports:
      - "5001:5000"
    volumes:
      - ./models:/app/models
    environment:
      - PORT=5000
      - MODEL_PATH=models/best_loan_prediction_model.pkl
    restart: unless-stopped